[rocks]
luacheck = "1.2.0"
nlua = "0.3.2"

[plugins]
"fidget.nvim" = "1.6.0"
"oil.nvim" = "2.15.0"
"rocks-config.nvim" = "3.1.2"
"rocks-treesitter.nvim" = "1.3.1"
"rocks.nvim" = "2.47.2"
"telescope-undo.nvim" = "scm"
"telescope.nvim" = "scm"
# Treesitter Parsers
tree-sitter-asm = "0.0.33"
tree-sitter-awk = "0.0.32"
tree-sitter-bash = "0.0.50"
tree-sitter-cmake = "0.0.40"
tree-sitter-commonlisp = "scm"
tree-sitter-cpp = "0.0.49"
tree-sitter-css = "0.0.39"
tree-sitter-dart = "0.0.37"
tree-sitter-desktop = "0.0.36"
tree-sitter-diff = "0.0.33"
tree-sitter-dockerfile = "0.0.30"
tree-sitter-git_config = "0.0.31"
tree-sitter-git_rebase = "scm"
tree-sitter-gitcommit = "scm"
tree-sitter-gitignore = "scm"
tree-sitter-go = "0.0.43"
tree-sitter-gomod = "0.0.35"
tree-sitter-gosum = "scm"
tree-sitter-gpg = "scm"
tree-sitter-haskell = "0.0.40"
tree-sitter-html = "0.0.40"
tree-sitter-hyprlang = "0.0.40"
tree-sitter-ini = "0.0.35"
tree-sitter-java = "0.0.46"
tree-sitter-javascript = "0.0.41"
tree-sitter-json = "0.0.40"
tree-sitter-json5 = "0.0.32"
tree-sitter-jsonc = "0.0.29"
tree-sitter-latex = "0.0.41"
tree-sitter-make = "scm"
tree-sitter-nginx = "0.0.31"
tree-sitter-nix = "0.0.69"
tree-sitter-ocaml = "scm"
tree-sitter-passwd = "0.0.29"
tree-sitter-perl = "0.0.48"
tree-sitter-python = "0.0.56"
tree-sitter-readline = "0.0.31"
tree-sitter-rst = "0.0.33"
tree-sitter-rust = "scm"
tree-sitter-sql = "0.0.51"
tree-sitter-ssh_config = "0.0.34"
tree-sitter-toml = "scm"
tree-sitter-typescript = "0.0.38"
tree-sitter-xml = "0.0.42"
tree-sitter-yaml = "scm"
tree-sitter-zsh = "0.0.10"

[config]
auto_setup = false
plugins_dir = "plugins"

[treesitter]
auto_highlight = "all"
auto_install = "prompt"

# [bundles]
telescope = { items = [ "telescope-undo.nvim", "telescope.nvim" ] }
